### ISSUE TITLE
Pet Warlock

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10314]
### Current Behaviour

**1)** Summon normally, pull the mount and descend... the pet disappears and consumes a soul.

**2)** I take a hit from the elite and the pet does not appear when dismounting to help the tank

https://user-images.githubusercontent.com/58153179/150649709-bab6b5fc-34af-4bd2-93e8-6b4f5ee4a9f5.mp4

### Expected Blizzlike Behaviour

Above

### Steps to reproduce the problem

Above

### AC rev. hash/commit

AzerothCore rev. b5ab409614bf+ 2022-01-18 20:25:17

### Operating system

Debian 10 x64

### Custom changes or Modules

None

**Comment by Winfidonarleyan** [comment]
i can't reproduce this in 7b041946e163224cb82ba85e734c9a757fa4209f

**Comment by acidmanifesto** [comment]
> ### Current Behaviour
> **1)** Summon normally, pull the mount and descend... the pet disappears and consumes a soul.
> 
> **2)** I take a hit from the elite and the pet does not appear when dismounting to help the tank
> 
>  Record_2022_01_20_18_57_39_399.mp4 
> ### Expected Blizzlike Behaviour
> Above
> 
> ### Source
> _No response_
> 
> ### Steps to reproduce the problem
> Above
> 
> ### Extra Notes
> _No response_
> 
> ### AC rev. hash/commit
> AzerothCore rev. [b5ab409](https://github.com/azerothcore/azerothcore-wotlk/commit/b5ab409614bf0d45e7a4f03c57b15edf113fe5f0)+ 2022-01-18 20:25:17
> 
> ### Operating system
> Debian 10 x64
> 
> ### Custom changes or Modules
> None

your version is well over a month old. can you do a update and recompile and report back to us?

**Comment by htc16** [comment]
yes, I am testing again with the new version.

**Comment by htc16** [comment]
This problem is solved, by some PR I don't know which one. But we can close this issue.

**Comment by Bocaj666** [comment]
Still bugged for me the entire last night, battlegrounds were unplayable.

What pet was summoned?
Voidwalker many times, I think maybe I tried Felhunter too, but cant remember 100%

Your level
60

Was it at full hp? Was it buffed?
It was at full health

After dismounting, was the pet there or unsummoned? Did you get a shard back?
The pet was not there and I did not get a shard back

If it came back, was the HP the same or not?
Did not come back

It all took place in warsong gulch, idk if it depends on location though. Many times it has worked for me in wsg but not last night.

**Comment by Scortas** [comment]
Have the same issue but closing the server and restarting it again seems to fix it at least so far.

Just in case is there a gm command that I can just spawn the pet without cast time if needed?

**Comment by haotienwang8** [comment]
What pet was summoned?: felhunter
Your level: 51
Was it at full hp?: yes 
Was it buffed? no
After dismounting, was the pet there or unsummoned? Unsummoned.
 Did you get a shard back? No.

**Comment by vildheden** [comment]
Just opened game this morning and on  char screen the felguard is there but when i log in and get off mount its not there - i summon it, mount up and mount off and still not there.. When I log out its still there on char screen.. Log back in and its back by my side and now it works after dis mount..

Regards Balkoth

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/10545
