### ISSUE TITLE
Command guild create fails when using space

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#17789]
### Current Behaviour

`.guild create player "Guild Name` - fails
`.guild create player "Guild"` - works

### Expected Blizzlike Behaviour

to work

### Steps to reproduce the problem

`.guild create player "Guild Name` - fails
`.guild create player "Guild"` - works

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/9ecb85acb5d8b8f71d9d103ea930096c1f4f4816

### Operating system

w11

**Comment by moterpent** [comment]
Can confirm.  Except in my case I can only create without quotes, with no spaces or other non-alpha characters.  Also there seem to be issues with rename as well.  Here are some examples:

```
.guild create Character TheGuild (successfully creates guild)
.guild delete TheGuild (successfully deletes guild)
.guild create Character "TheGuild" (fails with message message = "incorrect values")
.guild create Character "The Guild" (fails - shows syntax/usage)
.guild create Character The Guild (fails - shows syntax/usage)

.guild rename TheGuild "The Guild" (fails - syntax/usage)
.guild rename "TheGuild" "The Guild" (fails - syntax/usage)
.guild rename TheGuild MyGuild (fails - syntax/usage) 
```

AzerothCore rev. 9ecb85acb5d8 2023-11-19 11:57:37 +0700 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by moterpent** [comment]
Thank you for the update.  There's a subtle change when quotes are involved, but I'm still seeing issues  Examples:

```
.guild create Character TheGuild (failed - shows syntax/usage)
.guild create Character "TheGuild" (success)
.guild delete "TheGuild" (successfully deletes guild)

.guild create Character "The Guild" (failed - shows syntax/usage)
.guild create Character "The Guild" (fails - shows syntax/usage)
.guild create Character The Guild (fails - shows syntax/usage)

.guild rename "TheGuild" "The Guild" (fails - syntax/usage)
.guild rename "TheGuild" "NewGuild" (success) 
```

**Comment by elthehablo** [comment]
> Thank you for the update.  There's a subtle change when quotes are involved, but I'm still seeing issues  Examples:
> 
> ```
> .guild create Character TheGuild (failed - shows syntax/usage)
> .guild create Character "TheGuild" (success)
> .guild delete "TheGuild" (successfully deletes guild)
> 
> .guild create Character "The Guild" (failed - shows syntax/usage)
> .guild create Character The Guild (failed - shows syntax/usage)
> 
> .guild rename "TheGuild" "The Guild" (failed - syntax/usage)
> .guild rename "TheGuild" "NewGuild" (success) 
> ```

Yes I am aware of this issues. Spaces are broken

**Comment by moterpent** [comment]
> Yes I am aware of this issue. Spaces are broken

Thanks @elthehablo .  Wasn't sure given the issue was closed and topic was in regards to spaces not working.  Is it best to leave this open or open something new?

**Comment by elthehablo** [comment]
> 
> > Yes I am aware of this issue. Spaces are broken
> 
> Thanks @elthehablo .  Wasn't sure given the issue was closed and topic was in regards to spaces not working.  Is it best to leave this open or open something new?

Best to make a new specific issue about the spaces

**Comment by HanPrower** [comment]
Not sure why this is closed and OP is being told to make a new Bug Report when the title of this bug report is specifically about the spaces, not the quotes...

**Comment by Nyeriah** [comment]
@HanPrower because creating guild names with spaces has been fixed here https://github.com/azerothcore/azerothcore-wotlk/pull/17798 given you use the command properly

**Comment by HanPrower** [comment]
@Nyeriah #17798 is specifically titled "fix(Scripts/Commands): guild commands revert back to using guild names in quotes".

If you read the previous handful of comments the author of the PR even admits spaces are still broken :\

**Comment by Nyeriah** [comment]
will be fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/17863/files
