### ISSUE TITLE
.pinfo has weird latin character strings on latest revision

### ISSUE THREAD

**Issue by milestorme** [azerothcore/azerothcore-wotlk#2534]

**Comment by milestorme** [comment]
@Stoabrogga

**Comment by Stoabrogga** [comment]
@milestorme 
Could you please stop tagging me for all kind of issues? This project is a hobby to me, not a job, which means I'll only help if I _want_ to (and have the time / knowledge to do so). I'll regularly take a look at the issues and pick the ones where I want to help, so no need to tag me.

Btw, I can't help on this one either.

**Comment by milestorme** [comment]
You merged it that’s why I tagged you mate

**Comment by Stoabrogga** [comment]
Ok, but just because I merged something does not mean I'm responsible for the underlying PR. If a PR is labeled as "to be merged" it has to pass Travis and Codacy, must be reviewed by an AC staff member and must have been tested at least once, so there won't be any further checks for the actual merging of the PR.

In this case @Viste probably should take a look at the issue.

**Comment by milestorme** [comment]
sure thing bro , this is also a hobby for me to i work 6 days a week at a full time Job and i do this for fun and run my own server as a hobby , ill remember not to tag you from now on bro ;)

**Comment by Stoabrogga** [comment]
Except if you find errors or need information concerning my PRs. I also mostly have not the knowledge to help on the other PRs, e.g. I did not fully understand this UTF-8 PR because I'm too bad at C++.

**Comment by milestorme** [comment]
Yeah I can’t fix it either my c++ is still not that good , or I would have opened a pr to fix , I mean I could revert the changes but this might be needed and viste might have just overlooked something testing in his language that’s all

**Comment by FrancescoBorzi** [comment]
According to @milestorme , this PR caused the bug: https://github.com/azerothcore/azerothcore-wotlk/pull/2455

@Viste can you please take care of this?

**Comment by Viste** [comment]
@milestorme you can tag me because i block you little stupid monkey :) 
@FrancescoBorzi  yes, but here is a problem i cant build ACE on GCC/Clnag 9+ and i cant build the core to test :/ i need run a vm on Centos or Debian and this i can do only in 2020

**Comment by Stoabrogga** [comment]
Ok, just tested on commit 0d2999a (which includes the UTF-8 PR) and it looks good to me:
![grafik](https://user-images.githubusercontent.com/38475780/71547916-a6ebc280-29a6-11ea-8e66-fa1f5caa9a73.png)
I'll test this again once I have the time to update my server to the current version.

**Comment by milestorme** [comment]
> @milestorme you can tag me because i block you little stupid monkey :)
> @FrancescoBorzi yes, but here is a problem i cant build ACE on GCC/Clnag 9+ and that is why i cant build the core to test some things :/ i need run a VDS for this on Centos or Debian and this i can do only in 2020

ROFL love you

**Comment by milestorme** [comment]
still update to latest , maybe you can figure out which commit did this , I have confirmed reports latest commit has this

**Comment by BarbzYHOOL** [comment]
probably another invalid issue

**Comment by Stoabrogga** [comment]
Just for the sake of completeness: The `.pinfo` command also works correct on commit 561b9ba (tested on a new server with fresh DB).

**Comment by BarbzYHOOL** [comment]
haha as usual
